import Foundation
import Mobile  // gomobile-generated framework from the `mobile` Go package

/// Swift wrapper around the Go bridge core (via gomobile).
///
/// The Mobile framework is generated by running:
///   gomobile bind -target ios -o ios/MeshtasticHamBridge.xcframework \
///     github.com/dphilli/meshtastic-ham-bridge/mobile
public class BridgeManager: ObservableObject {

    @Published public var isRunning = false
    @Published public var statusMessage = "Stopped"

    private var bridge: MobileBridge? = nil  // MobileBridge = gomobile name for mobile.Bridge

    public init() {}

    deinit { stop() }

    // MARK: - Control

    /// Start using a config file. Pass nil to use the platform default path.
    public func start(configPath: String? = nil) {
        guard bridge == nil else { statusMessage = "Already running"; return }
        var error: NSError?
        let b = MobileStart(configPath ?? "", &error)
        if let error {
            statusMessage = "Error: \(error.localizedDescription)"
            return
        }
        bridge = b
        isRunning = true
        statusMessage = "Running"
    }

    /// Start with an explicit mesh serial port and audio device name.
    public func startAudio(meshPort: String, audioDevice: String = "") {
        guard bridge == nil else { statusMessage = "Already running"; return }
        var error: NSError?
        let b = MobileStartAudio(meshPort, audioDevice, &error)
        if let error {
            statusMessage = "Error: \(error.localizedDescription)"
            return
        }
        bridge = b
        isRunning = true
        statusMessage = "Running"
    }

    public func stop() {
        bridge?.stop()
        bridge = nil
        isRunning = false
        statusMessage = "Stopped"
    }

    // MARK: - Device discovery

    /// Returns available audio device names.
    public func listAudioDevices() -> [String] {
        var error: NSError?
        let result = MobileListAudioDevices(&error)
        guard error == nil, !result.isEmpty else { return [] }
        return result.split(separator: "\n").map(String.init)
    }
}
