package ham

import (
	"bufio"
	"fmt"
	"os"
	"strings"
	"text/template"
)

// direwolfConfigTemplate is a minimal Direwolf config for KISS TCP use.
// PTT is left unconfigured — user can add it manually or via rigctld.
var direwolfConfigTemplate = template.Must(template.New("dw").Parse(`
# Direwolf config generated by meshtastic-ham-bridge
# Edit this file to add PTT, digipeating, etc.

MYCALL {{.Callsign}}

ADEVICE {{.AudioDevice}}   # input output
ACHANNELS 1

CHANNEL 0
MODEM 1200

# KISS TCP port
KISSPORT {{.KISSPort}}
`))

type direwolfConfig struct {
	Callsign    string
	AudioDevice string
	KISSPort    int
}

// RunDirewolfSetup runs the interactive config wizard and writes configPath.
func RunDirewolfSetup(configPath string, kissPort int) error {
	r := bufio.NewReader(os.Stdin)

	// --- Callsign ---
	callsign, err := prompt(r, "Your callsign (e.g. W1AW): ")
	if err != nil {
		return err
	}
	callsign = strings.ToUpper(strings.TrimSpace(callsign))
	if callsign == "" {
		return fmt.Errorf("callsign is required")
	}

	// --- Audio devices (via malgo, indexed to handle duplicate names) ---
	outputs, err := ListAudioOutputsIndexed()
	if err != nil {
		return fmt.Errorf("listing audio output devices: %w", err)
	}
	inputs, err := ListAudioInputsIndexed()
	if err != nil {
		return fmt.Errorf("listing audio input devices: %w", err)
	}

	outDevice, err := pickAudioDevice(r, "output (transmit)", outputs)
	if err != nil {
		return err
	}
	inDevice, err := pickAudioDevice(r, "input (receive)", inputs)
	if err != nil {
		return err
	}

	// Direwolf ADEVICE format is: input output (receive then transmit)
	audioDevice := fmt.Sprintf("%q %q", inDevice.Name, outDevice.Name)

	// --- Write config ---
	cfg := direwolfConfig{
		Callsign:    callsign,
		AudioDevice: audioDevice,
		KISSPort:    kissPort,
	}

	f, err := os.Create(configPath)
	if err != nil {
		return fmt.Errorf("creating config %q: %w", configPath, err)
	}
	defer f.Close()

	if err := direwolfConfigTemplate.Execute(f, cfg); err != nil {
		return fmt.Errorf("writing config: %w", err)
	}

	fmt.Printf("\nConfig written to %q. Edit it to add PTT or digipeating.\n\n", configPath)
	return nil
}

func pickAudioDevice(r *bufio.Reader, label string, devices []AudioDeviceInfo) (AudioDeviceInfo, error) {
	if len(devices) == 0 {
		fmt.Printf("No %s devices found. Using device 0.\n", label)
		return AudioDeviceInfo{Index: 0, Name: "default"}, nil
	}
	fmt.Printf("\nAvailable audio %s devices:\n", label)
	for _, d := range devices {
		fmt.Printf("  [%d] %s\n", d.Index, d.Name)
	}
	choice, err := prompt(r, fmt.Sprintf("Select %s device number [0]: ", label))
	if err != nil {
		return AudioDeviceInfo{}, err
	}
	choice = strings.TrimSpace(choice)
	if choice == "" {
		return devices[0], nil
	}
	var idx int
	if _, err := fmt.Sscanf(choice, "%d", &idx); err != nil {
		return AudioDeviceInfo{}, fmt.Errorf("invalid selection %q", choice)
	}
	for _, d := range devices {
		if d.Index == idx {
			return d, nil
		}
	}
	return AudioDeviceInfo{}, fmt.Errorf("no device with index %d", idx)
}

func prompt(r *bufio.Reader, msg string) (string, error) {
	fmt.Print(msg)
	line, err := r.ReadString('\n')
	if err != nil {
		return "", fmt.Errorf("reading input: %w", err)
	}
	return strings.TrimRight(line, "\r\n"), nil
}
